name: update-metadata-v2

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "v2"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - run: pip install aiohttp packaging

      - name: Update metadata
        run: ./metadata.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "metadata.json: Update"
          commit-message: "metadata.json: Update"

          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

          branch: "update_metadata"
          delete-branch: true
